// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.19.1

/* eslint-disable */

export * as google from "./index.google";
export * as friendcrm from "./index.friendcrm";
