name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary

      - name: Compile
        run: ./compile-all.sh

      - name: Print output
        run: |
          cd out
          ls -la
